### ISSUE TITLE
VSTS dashboard widget showing wrong release

### ISSUE THREAD

**Issue by ichivers** [OctopusDeploy/OctoTFS#78] opened 2017-03-28 14:33 UTC
Using Octopus server 3.3.11

Here is a screenshot of the project and environment from Octopus

![octopus](https://cloud.githubusercontent.com/assets/5063940/24410739/bc6e155c-13cb-11e7-90db-1c2dc479d06d.PNG)

...and here's what it looks like in the widget

![vsts - octopus](https://cloud.githubusercontent.com/assets/5063940/24410730/b6533a62-13cb-11e7-94f0-cc0754927ed7.PNG)

**Comment by mcasperson** [comment] 2018-03-27 02:52
I attempted to reproduce this error with version 2.0.98 of the TFS plugin and Octopus 2018.3.7, but I was unable to get the widget to display an incorrect version. Given this issue was raised against Octopus 3.3.11 it appears that it has since been resolved.

I'll close this issue as it can not be reproduced.

@ichivers If this is still an issue with recent versions of Octopus, please leave a comment and we can reopen this ticket.

**Closed by mcasperson** 2018-03-27 02:52 UTC
