### ISSUE TITLE
Task fails when running in Release in VSTS (ex-VSO)

### ISSUE THREAD

**Issue by trailmax** [OctopusDeploy/OctoTFS#33] opened 2016-01-28 23:31 UTC
I'm executing Create Octopus Release step in Release mode in Visual Studio Team Services. But I get an error saying `Cannot bind argument to parameter 'Path' because it is null.`

I run the same step as a Build step and everything works fine. Sound like the same issue as #29, but I'm unsure if error is the same. Here is my log: 
[vso_createRelease.txt](https://github.com/OctopusDeploy/OctoTFS/files/109048/vso_createRelease.txt)

Also the problem looks the same as I had with executing Publish NuGet script in Release (http://stackoverflow.com/q/34790751/809357) and the solution for that problem was like this: https://github.com/Microsoft/vso-agent-tasks/pull/1034/files

**Comment by Damovisa** [comment] 2016-02-18 03:41
Hi @trailmax,

Are you able to update the extension (if you're using on-prem - otherwise it should stay up to date) and try again? We've recently made some changes that may have fixed the issue.

If not, let me know and I'll investigate a bit further.

Damian

**Comment by trailmax** [comment] 2016-02-18 10:31
Hi Damian

I have tried re-running this and the same problem persists. I can see the version numbers have changed from the last log, but the error is the same: 
[4_Create Octopus Release.txt](https://github.com/OctopusDeploy/OctoTFS/files/136028/4_Create.Octopus.Release.txt)

I'm using VSTS hosted service - nothing on-prem, so it should be updated when you update the plugin.

Many thanks,
Max

**Comment by Damovisa** [comment] 2016-02-18 22:59
Hi Max,

I think I know what might be happening and it's likely to be the same as #29 as you suggested. The code is using a build-specific environment variable rather than one that's applicable to build and release modes.

I'll work on a fix and have an update soon.

Thanks,
Damian

**Comment by trailmax** [comment] 2016-02-18 23:29
Thanks, Damian, much appreciated. For my current small-ish projects I'm creating a release in Octopus as a build step and it is OK. But in order to migrate my larger projects it'll be nice to have VSTS Release functionality working so not every build is deployed.

**Comment by michaelnoonan** [comment] 2016-04-03 23:16
I'm going to close this issue as a duplicate of https://github.com/OctopusDeploy/OctoTFS/issues/29 and track the remainder of the work in that issue.

**Closed by michaelnoonan** 2016-04-03 23:16 UTC
